### ISSUE TITLE
a bug?

### ISSUE THREAD

**Issue by dedomraz** [nouun/3cac#2]
hey!
running it on win 10, i get this error, it started appr. a week ago(update to latest ver. did not help):

```
npm run run

> 3cac@1.1.0 run
> node .

-- Fetching bubbles
undefined:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Response.json (file:///I:/crypto_data/3cac/node_modules/node-fetch/src/body.js:149:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async fetchBubbles (file:///I:/crypto_data/3cac/dist/lib.js:5:12)
    at async run (file:///I:/crypto_data/3cac/dist/index.js:59:25)
    at async loopWithDelay (file:///I:/crypto_data/3cac/dist/index.js:192:13)
```

thanks a lot for your time and effort!

**Comment by dedomraz** [comment]
found the culprit => cryptobubbles changed the json address to: https://cryptobubbles.net/backend/data/bubbles1000.<spot>.json ie. https://cryptobubbles.net/backend/data/bubbles1000.usd.json

changed the value in /dist/lib.js:5:12

however there is a new issue:
```
> 3cac@1.1.0 run
> node .

-- Fetching bubbles
-- Fetching bots
++ Updating <bot name>
-- Fetching valid pairs for binance
file:///I:/crypto_data/3cac/dist/index.js:75
                const data = bubble.data.usd;
                                         ^

TypeError: Cannot read properties of undefined (reading 'usd')
    at file:///I:/crypto_data/3cac/dist/index.js:75:42
    at Array.filter (<anonymous>)
    at run (file:///I:/crypto_data/3cac/dist/index.js:74:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async loopWithDelay (file:///I:/crypto_data/3cac/dist/index.js:192:13)
```

my knowledge probably ends here... thank you for your support!

**Comment by dedomraz** [comment]
i made it!

change this in dist\index.js:
row 75 `const data = bubble.data.usd; `
into: 
`const data = bubble;`

row 92 `.sort((bubble1, bubble2) => bubble2.data.usd.performance[botConfig.filter?.performance?.sort ?? "hour"] -`
row 93 `bubble1.data.usd.performance[botConfig.filter?.performance?.sort ?? "hour"])`
into:
```
.sort((bubble1, bubble2) => bubble2.performance[botConfig.filter?.performance?.sort ?? "hour"] -
bubble1.performance[botConfig.filter?.performance?.sort ?? "hour"])
```

row 137 `printPairs();`
into:
```
if (pairs.length != 0){
printPairs()};
```

row 150 `return;`
into:
`continue;`

row 159 `return;`
into:
`continue;`

row 165 `return;`
into:
`continue;`


file: dist\lib.js

row 2 `const CB_API = "https://cryptobubbles.net/backend/data/currentBubbles500.json";`
into:
`const CB_API = "https://cryptobubbles.net/backend/data/bubbles1000.usd.json";`

^ this will however make the 3cac usable only for USD, if you want other spot, change the usd something else from here: https://cryptobubbles.net/backend/data/bubbles1000.json

hope i helped...
